import { SetupDefinition } from "./types.js";

export function defaultSetupCatalog(): SetupDefinition[] {
  return [
    {
      name: "distance_dom_neg30_15_late",
      family: "distance_dominance",
      description: "Buy dominant side when BTC is 15-30 bps below target with 15-60s remaining.",
      sideMode: "dominant",
      secondsRemaining: { min: 15, max: 60 },
      signedDistanceBps: { min: -30, max: -15 },
      maxEntryAsk: 0.75,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "distance_dom_neg30_15_mid",
      family: "distance_dominance",
      description: "Buy dominant side when BTC is 15-30 bps below target with 60-180s remaining.",
      sideMode: "dominant",
      secondsRemaining: { min: 60, max: 180 },
      signedDistanceBps: { min: -30, max: -15 },
      maxEntryAsk: 0.78,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "distance_dom_neg15_5_late",
      family: "distance_dominance",
      description: "Buy dominant side when BTC is 5-15 bps below target with 30-60s remaining.",
      sideMode: "dominant",
      secondsRemaining: { min: 30, max: 60 },
      signedDistanceBps: { min: -15, max: -5 },
      minEntryAsk: 0.55,
      maxEntryAsk: 0.86,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "distance_dom_sigma_180_240",
      family: "distance_dominance",
      description: "Buy dominant side 180-240s out when distance is 1-5 sigma.",
      sideMode: "dominant",
      secondsRemaining: { min: 180, max: 240 },
      distanceSigma: { min: 1, max: 5 },
      maxEntryAsk: 0.75,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "distance_rev_pos15_30_control",
      family: "distance_reversal_control",
      description: "Control: buy reversal side when BTC is 15-30 bps above target with 60-120s remaining.",
      sideMode: "reversal",
      secondsRemaining: { min: 60, max: 120 },
      signedDistanceBps: { min: 15, max: 30 },
      maxEntryAsk: 0.30,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "distance_rev_near_tie_control",
      family: "distance_reversal_control",
      description: "Control: buy reversal side close to target with 120-180s remaining.",
      sideMode: "reversal",
      secondsRemaining: { min: 120, max: 180 },
      signedDistanceBps: { min: -5, max: 5 },
      maxEntryAsk: 0.50,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "crossing_reversal_chop_near",
      family: "crossing_probability",
      description: "Buy reversal side in choppy near-target regimes with at least 3 crosses in-window.",
      sideMode: "reversal",
      secondsRemaining: { min: 30, max: 120 },
      signedDistanceBps: { min: -15, max: 15 },
      minCrosses: 3,
      maxSecondsSinceCross: 90,
      maxEntryAsk: 0.45,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "crossing_reversal_fresh_cross",
      family: "crossing_probability",
      description: "Buy reversal side shortly after a recent cross when price remains close to target.",
      sideMode: "reversal",
      secondsRemaining: { min: 15, max: 90 },
      signedDistanceBps: { min: -10, max: 10 },
      minCrosses: 1,
      maxSecondsSinceCross: 30,
      maxEntryAsk: 0.50,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "crossing_dominance_failed_revert",
      family: "crossing_probability",
      description: "Buy dominant side when multiple crosses occurred but current distance is already 15-30 bps.",
      sideMode: "dominant",
      secondsRemaining: { min: 30, max: 120 },
      signedDistanceBps: { min: 15, max: 30 },
      minCrosses: 2,
      maxEntryAsk: 0.75,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "crossing_dominance_down_failed_revert",
      family: "crossing_probability",
      description: "Buy dominant side when multiple crosses occurred but current distance is -30 to -15 bps.",
      sideMode: "dominant",
      secondsRemaining: { min: 30, max: 120 },
      signedDistanceBps: { min: -30, max: -15 },
      minCrosses: 2,
      maxEntryAsk: 0.75,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "near_target_reversal_late_sigma05",
      family: "near_target_locked",
      description: "Buy reversal side late when BTC is within 5 bps and within 0.5 sigma of target.",
      sideMode: "reversal",
      secondsRemaining: { min: 15, max: 60 },
      signedDistanceBps: { min: -5, max: 5 },
      distanceSigma: { min: 0, max: 0.5 },
      maxEntryAsk: 0.45,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "near_target_reversal_mid_sigma1",
      family: "near_target_locked",
      description: "Buy reversal side with 60-180s remaining when BTC is within 5 bps and 1 sigma of target.",
      sideMode: "reversal",
      secondsRemaining: { min: 60, max: 180 },
      signedDistanceBps: { min: -5, max: 5 },
      distanceSigma: { min: 0, max: 1 },
      maxEntryAsk: 0.50,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "near_target_dominance_late_control",
      family: "near_target_locked",
      description: "Control: buy dominant side late near target only if not priced above 65c.",
      sideMode: "dominant",
      secondsRemaining: { min: 15, max: 60 },
      signedDistanceBps: { min: -5, max: 5 },
      distanceSigma: { min: 0, max: 1 },
      maxEntryAsk: 0.65,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "near_target_reversal_crossed_late",
      family: "near_target_locked",
      description: "Buy reversal side near target late only after at least one in-window cross.",
      sideMode: "reversal",
      secondsRemaining: { min: 15, max: 60 },
      signedDistanceBps: { min: -5, max: 5 },
      distanceSigma: { min: 0, max: 1 },
      minCrosses: 1,
      maxSecondsSinceCross: 120,
      maxEntryAsk: 0.45,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "lag_continuation_30s_dom_cheap",
      family: "lag_btc_vs_odds",
      description: "Buy dominant side when 30s BTC momentum confirms the dominant side but ask remains below 70c.",
      sideMode: "dominant",
      secondsRemaining: { min: 30, max: 120 },
      signedDistanceBps: { min: -30, max: 30 },
      momentumWindowSec: 30,
      minMomentumBps: 4,
      momentumDirection: "dominant",
      maxEntryAsk: 0.70,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "lag_continuation_10s_dom_cheap",
      family: "lag_btc_vs_odds",
      description: "Buy dominant side when 10s BTC momentum confirms the dominant side but ask remains below 65c.",
      sideMode: "dominant",
      secondsRemaining: { min: 15, max: 90 },
      signedDistanceBps: { min: -20, max: 20 },
      momentumWindowSec: 10,
      minMomentumBps: 2,
      momentumDirection: "dominant",
      maxEntryAsk: 0.65,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "lag_reversal_30s_countermove",
      family: "lag_btc_vs_odds",
      description: "Control: buy reversal side when 30s BTC momentum runs against current dominant side.",
      sideMode: "reversal",
      secondsRemaining: { min: 30, max: 120 },
      signedDistanceBps: { min: -30, max: 30 },
      momentumWindowSec: 30,
      minMomentumBps: 4,
      momentumDirection: "reversal",
      maxEntryAsk: 0.45,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "lag_dominance_strong_move",
      family: "lag_btc_vs_odds",
      description: "Buy dominant side on stronger 30s BTC move if market still offers below 80c.",
      sideMode: "dominant",
      secondsRemaining: { min: 30, max: 180 },
      signedDistanceBps: { min: -50, max: 50 },
      momentumWindowSec: 30,
      minMomentumBps: 8,
      momentumDirection: "dominant",
      maxEntryAsk: 0.80,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "late_momentum_10s_dom_75",
      family: "late_momentum_continuation",
      description: "Buy dominant side in final 5-30s on 10s confirming BTC momentum if ask is below 75c.",
      sideMode: "dominant",
      secondsRemaining: { min: 5, max: 30 },
      signedDistanceBps: { min: -30, max: 30 },
      momentumWindowSec: 10,
      minMomentumBps: 2,
      momentumDirection: "dominant",
      maxEntryAsk: 0.75,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "late_momentum_30s_dom_80",
      family: "late_momentum_continuation",
      description: "Buy dominant side in final 5-30s on 30s confirming BTC momentum if ask is below 80c.",
      sideMode: "dominant",
      secondsRemaining: { min: 5, max: 30 },
      signedDistanceBps: { min: -40, max: 40 },
      momentumWindowSec: 30,
      minMomentumBps: 5,
      momentumDirection: "dominant",
      maxEntryAsk: 0.80,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    },
    {
      name: "late_momentum_reversal_counter",
      family: "late_momentum_continuation",
      description: "Control: buy reversal side in final 5-30s when BTC momentum is counter to current dominant side.",
      sideMode: "reversal",
      secondsRemaining: { min: 5, max: 30 },
      signedDistanceBps: { min: -30, max: 30 },
      momentumWindowSec: 10,
      minMomentumBps: 2,
      momentumDirection: "reversal",
      maxEntryAsk: 0.45,
      latencyMs: 500,
      slippagePrice: 0.01,
      oneTradePerMarket: true
    }
  ];
}
